#!/bin/bash
#
# pfind - Prettier than find

version='1.2'

# Get execution name of script
exec_name() {
	local name=$1
	local basename=$(basename "$name")
	mapfile -td: path < <(printf "$PATH")
	for dir in "${path[@]}"; do
		if [[ $name == $dir/$basename ]]; then
			name=$basename
			break
		fi
	done
	printf "$name"
}

show_help() {
	local myname=$(exec_name "$0")
	echo -n "\
pfind v$version
Prettier than find

  Usage: $myname [find-options] [starting-point...] [expression]
"'
Arguments are identical to those of `find`.  See `man find`, `info find`, or
`find -h` for details.
'
	exit 0
}

# Process commandline args
while [[ $1 == -* ]]; do
	case "$1" in
		-h | --help ) show_help ;;
		* )           break     ;;
	esac
	shift
done

mapfile -t files < <(find "$@")
ls -aldh --color=auto "${files[@]}"
