#!/bin/bash
#
# pfind - Prettier than find

version='1.1'

myname=$(basename "$0")

show_help() {
	echo -n "\
pfind v$version
Prettier than find

  Usage: $myname [find-options] [starting-point...] [expression]
"'
Arguments are identical to those of `find`.  See `man find`, `info find`, or
`find -h` for details.
'
	exit 0
}

# Process commandline args
while [[ $1 == -* ]]; do
	case "$1" in
		-h | --help ) show_help ;;
		* )           break     ;;
	esac
	shift
done

mapfile -t files < <(find "$@")
ls -aldh --color=auto "${files[@]}"
