#!/bin/sh
#
# wanip - Returns External IP address

version='1.2'

# Shortcut to check command existence
iscommand() { command -v "$@" >/dev/null 2>&1; }

show_help() {
	echo -n "
wanip v$version
Print the system's Internet-visible IP address to stdout

  Usage: wanip [-v|-h]

Options:
  -v | --verbose   Show more information on stderr
  -h | --help      Show this help info
"
	exit 0
}

# Process commandline args
while [ $# -gt 0 ]; do
	case "$1" in
		-v | --verbose ) verbose=true ;;
		-h | --help    ) show_help    ;;
		* )
			echo "Unknown option '$1' (Try 'wanip --help')" >&2
			exit 1
			;;
	esac
	shift
done

if iscommand dig; then
	[ -n "$verbose" ] && echo "Using dig..." >&2
	dig +short myip.opendns.com @resolver1.opendns.com || exit 1
elif iscommand curl; then
	[ -n "$verbose" ] && echo "Using curl..." >&2
	curl http://whatismyip.akamai.com/ && echo || exit 1
else
	echo "Error: Install either dig or curl" >&2
	exit 2
fi
