#!/bin/sh
#
# wanip - Returns External IP address

version='1.4'

# Portable version of `echo`
print () { printf '%s\n' "$*"; }

# Shortcut to check command existence
iscommand() { command -v "$@" >/dev/null 2>&1; }

show_help() {
	cat << EOF
wanip v$version
Print the system's Internet-visible IP address to stdout

  Usage: wanip [-c|-d|-v|-h] ...

Options:
  -c | --curl      Always use curl
  -d | --dig       Always use dig
  -v | --verbose   Show more information on stderr
  -h | --help      Show this help info
EOF
	exit 0
}

use=''

# Process commandline args
while [ $# -gt 0 ]; do
	case "$1" in
		-c | --curl    ) use=curl     ;;
		-d | --dig     ) use=dig      ;;
		-v | --verbose ) verbose=true ;;
		-h | --help    ) show_help    ;;
		* )
			print >&2 "Unknown option '$1' (Try 'wanip --help')"
			exit 1
			;;
	esac
	shift
done

if [ -n "$use" ]; then
	iscommand "$use" || {
		print >&2 "Error: $use is not installed"
		exit 2
	}
else
	if iscommand dig; then
		use=dig
	elif iscommand curl; then
		use=curl
	else
		print >&2 "Error: Install either dig or curl"
		exit 2
	fi
fi

[ -n "$verbose" ] && print >&2 "Using $use..."

case "$use" in
dig)
	dig @resolver1.opendns.com myip.opendns.com ANY +short +notcp || exit 1 ;;
curl)
	curl http://whatismyip.akamai.com/ && print || exit 1 ;;
*)
	print >&2 "Error: Unknown internal error occurred"
	exit 99
	;;
esac
